version: 2.1

jobs:
  build:
    docker:
      - image: "cimg/python:3.8.11"
    steps:
      - checkout
      - run: python3 phonemapper/phonemapper.py
  test:
    docker:
      - image: "cimg/python:3.8.11"
    steps:
      - checkout
      - run: python -m unittest test.test_phonemapper

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

